FROM balenalib/amd64-ubuntu-node:14-bionic-20221215

# Create app directory
WORKDIR /usr/src/app

RUN apt-get update 
RUN apt-get install -y build-essential libssl-dev
RUN apt-get install -y wget gnupg curl

# RUN curl -sL https://deb.nodesource.com/setup_14.x
# RUN apt-get install -y nodejs
# RUN apt-get install -y npm

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - 
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' 
RUN apt-get update 
RUN apt-get install -y libnss3 --no-install-recommends 
RUN apt-get install -y chromium-browser --no-install-recommends
RUN apt-get install -y gconf-service --no-install-recommends
RUN apt-get install -y libgbm-dev --no-install-recommends
RUN apt-get install -y libasound2 --no-install-recommends
RUN apt-get install -y libatk1.0-0 --no-install-recommends
RUN apt-get install -y libc6 --no-install-recommends
RUN apt-get install -y libcairo2 --no-install-recommends
RUN apt-get install -y libcups2 --no-install-recommends
RUN apt-get install -y libdbus-1-3 --no-install-recommends
RUN apt-get install -y libexpat1 --no-install-recommends
RUN apt-get install -y libfontconfig1 --no-install-recommends
RUN apt-get install -y libgcc1 --no-install-recommends
RUN apt-get install -y libgconf-2-4 --no-install-recommends
RUN apt-get install -y google-chrome-stable --no-install-recommends
RUN apt-get install -y fonts-ipafont-gothic --no-install-recommends
RUN apt-get install -y fonts-wqy-zenhei --no-install-recommends
RUN apt-get install -y fonts-thai-tlwg --no-install-recommends
RUN apt-get install -y fonts-kacst --no-install-recommends
RUN apt-get install -y fonts-freefont-ttf --no-install-recommends
RUN apt-get install -y libasound2:amd64

RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN apt-get install ./google-chrome-stable_current_amd64.deb

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install -g typescript

RUN npm install

# RUN npm run build
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

RUN npm run build

EXPOSE 8080
CMD [ "node", "lib/index.js" ]